# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  # Python依赖更新
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    labels:
      - "dependencies"
      - "python"
    reviewers:
      - "tsinglinrain"  # 替换为你的GitHub用户名
    open-pull-requests-limit: 5
    
  # Dockerfile依赖更新
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "09:00"
    labels:
      - "dependencies"
      - "docker"
    reviewers:
      - "tsinglinrain"  # 替换为你的GitHub用户名
    open-pull-requests-limit: 3
    
  # Docker Compose更新（如果有多个compose文件，可能需要多个配置）
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "09:30"
    labels:
      - "dependencies"
      - "docker-compose"
    reviewers:
      - "tsinglinrain"  # 替换为你的GitHub用户名
    
  # GitHub Actions workflow更新
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
      time: "10:00"
    labels:
      - "dependencies"
      - "github-actions"
    reviewers:
      - "tsinglinrain"  # 替换为你的GitHub用户名
    open-pull-requests-limit: 2
