name: Docker Build and Push

on:
  push:
    branches: [ "feat/add-flask" ]

env:
  IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/yuriaudio2notion

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push (Safe Mode)
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:latest
            ${{ env.IMAGE_NAME }}:${{ github.sha }}
          # 关键修复：禁用所有高级功能
          platforms: linux/amd64  # 仅构建单架构
          cache-from: ''          # 禁用缓存
          cache-to: ''            # 禁用缓存